
package main.java.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookingWSService", targetNamespace = "http://services.web/", wsdlLocation = "http://localhost:8080/ServicioWebSOAP/soapws/booking?wsdl")
public class BookingWSService
    extends Service
{

    private final static URL BOOKINGWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKINGWSSERVICE_EXCEPTION;
    private final static QName BOOKINGWSSERVICE_QNAME = new QName("http://services.web/", "BookingWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServicioWebSOAP/soapws/booking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKINGWSSERVICE_WSDL_LOCATION = url;
        BOOKINGWSSERVICE_EXCEPTION = e;
    }

    public BookingWSService() {
        super(__getWsdlLocation(), BOOKINGWSSERVICE_QNAME);
    }

    public BookingWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKINGWSSERVICE_QNAME, features);
    }

    public BookingWSService(URL wsdlLocation) {
        super(wsdlLocation, BOOKINGWSSERVICE_QNAME);
    }

    public BookingWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKINGWSSERVICE_QNAME, features);
    }

    public BookingWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBookingWS
     */
    @WebEndpoint(name = "BookingWSPort")
    public IBookingWS getBookingWSPort() {
        return super.getPort(new QName("http://services.web/", "BookingWSPort"), IBookingWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBookingWS
     */
    @WebEndpoint(name = "BookingWSPort")
    public IBookingWS getBookingWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.web/", "BookingWSPort"), IBookingWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKINGWSSERVICE_EXCEPTION!= null) {
            throw BOOKINGWSSERVICE_EXCEPTION;
        }
        return BOOKINGWSSERVICE_WSDL_LOCATION;
    }

}
