
package main.java.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientWSService", targetNamespace = "http://services.web/", wsdlLocation = "http://localhost:8080/ServicioWebSOAP/soapws/client?wsdl")
public class ClientWSService
    extends Service
{

    private final static URL CLIENTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTWSSERVICE_EXCEPTION;
    private final static QName CLIENTWSSERVICE_QNAME = new QName("http://services.web/", "ClientWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServicioWebSOAP/soapws/client?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTWSSERVICE_WSDL_LOCATION = url;
        CLIENTWSSERVICE_EXCEPTION = e;
    }

    public ClientWSService() {
        super(__getWsdlLocation(), CLIENTWSSERVICE_QNAME);
    }

    public ClientWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTWSSERVICE_QNAME, features);
    }

    public ClientWSService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTWSSERVICE_QNAME);
    }

    public ClientWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTWSSERVICE_QNAME, features);
    }

    public ClientWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IClientWS
     */
    @WebEndpoint(name = "ClientWSPort")
    public IClientWS getClientWSPort() {
        return super.getPort(new QName("http://services.web/", "ClientWSPort"), IClientWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IClientWS
     */
    @WebEndpoint(name = "ClientWSPort")
    public IClientWS getClientWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.web/", "ClientWSPort"), IClientWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTWSSERVICE_EXCEPTION!= null) {
            throw CLIENTWSSERVICE_EXCEPTION;
        }
        return CLIENTWSSERVICE_WSDL_LOCATION;
    }

}
