
package main.java.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelWS", targetNamespace = "http://services.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns main.java.webservice.Hotel
     * @throws HotelException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listHotel", targetNamespace = "http://services.web/", className = "main.java.webservice.ListHotel")
    @ResponseWrapper(localName = "listHotelResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.ListHotelResponse")
    @Action(input = "http://services.web/IHotelWS/listHotelRequest", output = "http://services.web/IHotelWS/listHotelResponse", fault = {
        @FaultAction(className = HotelException_Exception.class, value = "http://services.web/IHotelWS/listHotel/Fault/HotelException")
    })
    public Hotel listHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws HotelException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<main.java.webservice.Hotel>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listHotels", targetNamespace = "http://services.web/", className = "main.java.webservice.ListHotels")
    @ResponseWrapper(localName = "listHotelsResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.ListHotelsResponse")
    @Action(input = "http://services.web/IHotelWS/listHotelsRequest", output = "http://services.web/IHotelWS/listHotelsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://services.web/IHotelWS/listHotels/Fault/Exception")
    })
    public List<Hotel> listHotels()
        throws Exception_Exception
    ;

}
