
package main.java.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRoomWS", targetNamespace = "http://services.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRoomWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws RoomException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRoom", targetNamespace = "http://services.web/", className = "main.java.webservice.DeleteRoom")
    @ResponseWrapper(localName = "deleteRoomResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.DeleteRoomResponse")
    @Action(input = "http://services.web/IRoomWS/deleteRoomRequest", output = "http://services.web/IRoomWS/deleteRoomResponse", fault = {
        @FaultAction(className = RoomException_Exception.class, value = "http://services.web/IRoomWS/deleteRoom/Fault/RoomException")
    })
    public String deleteRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws RoomException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<main.java.webservice.RoomDTO>
     * @throws HotelException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listRoomsOfHotel", targetNamespace = "http://services.web/", className = "main.java.webservice.ListRoomsOfHotel")
    @ResponseWrapper(localName = "listRoomsOfHotelResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.ListRoomsOfHotelResponse")
    @Action(input = "http://services.web/IRoomWS/listRoomsOfHotelRequest", output = "http://services.web/IRoomWS/listRoomsOfHotelResponse", fault = {
        @FaultAction(className = HotelException_Exception.class, value = "http://services.web/IRoomWS/listRoomsOfHotel/Fault/HotelException")
    })
    public List<RoomDTO> listRoomsOfHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws HotelException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws HotelException_Exception
     * @throws RoomException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRoom", targetNamespace = "http://services.web/", className = "main.java.webservice.AddRoom")
    @ResponseWrapper(localName = "addRoomResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.AddRoomResponse")
    @Action(input = "http://services.web/IRoomWS/addRoomRequest", output = "http://services.web/IRoomWS/addRoomResponse", fault = {
        @FaultAction(className = RoomException_Exception.class, value = "http://services.web/IRoomWS/addRoom/Fault/RoomException"),
        @FaultAction(className = HotelException_Exception.class, value = "http://services.web/IRoomWS/addRoom/Fault/HotelException")
    })
    public String addRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        RoomAddDTO arg0)
        throws HotelException_Exception, RoomException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws RoomException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRoom", targetNamespace = "http://services.web/", className = "main.java.webservice.UpdateRoom")
    @ResponseWrapper(localName = "updateRoomResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.UpdateRoomResponse")
    @Action(input = "http://services.web/IRoomWS/updateRoomRequest", output = "http://services.web/IRoomWS/updateRoomResponse", fault = {
        @FaultAction(className = RoomException_Exception.class, value = "http://services.web/IRoomWS/updateRoom/Fault/RoomException")
    })
    public String updateRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        RoomDTO arg0)
        throws RoomException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns main.java.webservice.RoomDTO
     * @throws RoomException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listRoom", targetNamespace = "http://services.web/", className = "main.java.webservice.ListRoom")
    @ResponseWrapper(localName = "listRoomResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.ListRoomResponse")
    @Action(input = "http://services.web/IRoomWS/listRoomRequest", output = "http://services.web/IRoomWS/listRoomResponse", fault = {
        @FaultAction(className = RoomException_Exception.class, value = "http://services.web/IRoomWS/listRoom/Fault/RoomException")
    })
    public RoomDTO listRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws RoomException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<main.java.webservice.RoomDTO>
     * @throws BookingException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listRoomsOfBooking", targetNamespace = "http://services.web/", className = "main.java.webservice.ListRoomsOfBooking")
    @ResponseWrapper(localName = "listRoomsOfBookingResponse", targetNamespace = "http://services.web/", className = "main.java.webservice.ListRoomsOfBookingResponse")
    @Action(input = "http://services.web/IRoomWS/listRoomsOfBookingRequest", output = "http://services.web/IRoomWS/listRoomsOfBookingResponse", fault = {
        @FaultAction(className = BookingException_Exception.class, value = "http://services.web/IRoomWS/listRoomsOfBooking/Fault/BookingException")
    })
    public List<RoomDTO> listRoomsOfBooking(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws BookingException_Exception
    ;

}
