
package main.java.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RoomException", targetNamespace = "http://services.web/")
public class RoomException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RoomException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RoomException_Exception(String message, RoomException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RoomException_Exception(String message, RoomException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: main.java.webservice.RoomException
     */
    public RoomException getFaultInfo() {
        return faultInfo;
    }

}
