
package main.java.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoomWSService", targetNamespace = "http://services.web/", wsdlLocation = "http://localhost:8080/ServicioWebSOAP/soapws/room?wsdl")
public class RoomWSService
    extends Service
{

    private final static URL ROOMWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROOMWSSERVICE_EXCEPTION;
    private final static QName ROOMWSSERVICE_QNAME = new QName("http://services.web/", "RoomWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServicioWebSOAP/soapws/room?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROOMWSSERVICE_WSDL_LOCATION = url;
        ROOMWSSERVICE_EXCEPTION = e;
    }

    public RoomWSService() {
        super(__getWsdlLocation(), ROOMWSSERVICE_QNAME);
    }

    public RoomWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROOMWSSERVICE_QNAME, features);
    }

    public RoomWSService(URL wsdlLocation) {
        super(wsdlLocation, ROOMWSSERVICE_QNAME);
    }

    public RoomWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROOMWSSERVICE_QNAME, features);
    }

    public RoomWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRoomWS
     */
    @WebEndpoint(name = "RoomWSPort")
    public IRoomWS getRoomWSPort() {
        return super.getPort(new QName("http://services.web/", "RoomWSPort"), IRoomWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRoomWS
     */
    @WebEndpoint(name = "RoomWSPort")
    public IRoomWS getRoomWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.web/", "RoomWSPort"), IRoomWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROOMWSSERVICE_EXCEPTION!= null) {
            throw ROOMWSSERVICE_EXCEPTION;
        }
        return ROOMWSSERVICE_WSDL_LOCATION;
    }

}
