
package main.java.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceWSService", targetNamespace = "http://services.web/", wsdlLocation = "http://localhost:8080/ServicioWebSOAP/soapws/service?wsdl")
public class ServiceWSService
    extends Service
{

    private final static URL SERVICEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEWSSERVICE_EXCEPTION;
    private final static QName SERVICEWSSERVICE_QNAME = new QName("http://services.web/", "ServiceWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServicioWebSOAP/soapws/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEWSSERVICE_WSDL_LOCATION = url;
        SERVICEWSSERVICE_EXCEPTION = e;
    }

    public ServiceWSService() {
        super(__getWsdlLocation(), SERVICEWSSERVICE_QNAME);
    }

    public ServiceWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEWSSERVICE_QNAME, features);
    }

    public ServiceWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEWSSERVICE_QNAME);
    }

    public ServiceWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEWSSERVICE_QNAME, features);
    }

    public ServiceWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceWS
     */
    @WebEndpoint(name = "ServiceWSPort")
    public IServiceWS getServiceWSPort() {
        return super.getPort(new QName("http://services.web/", "ServiceWSPort"), IServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceWS
     */
    @WebEndpoint(name = "ServiceWSPort")
    public IServiceWS getServiceWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.web/", "ServiceWSPort"), IServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEWSSERVICE_EXCEPTION!= null) {
            throw SERVICEWSSERVICE_EXCEPTION;
        }
        return SERVICEWSSERVICE_WSDL_LOCATION;
    }

}
